services:
  genggam-makna-api:
    image: "vinssdroid/genggam-makna-ml-api:v1"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genggam-makna-ml-api
    env_file:
      - /etc/secrets/genggam-makna-ml-api.env
    ports:
      - "4014:4014"
    networks:
      - nginx-mailcow-host
    volumes:
      - /etc/secrets:/etc/secrets
    command:
      ["python3", "./app.py"]

networks:
  nginx-mailcow-host:
    external: true